gin:
  host: 0.0.0.0
  port: 8080

mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  db_name: blog
  #max_open_conns:打开到数据库的最大连接数。如果小于等于0，则对打开的连接数没有限制。
  max_open_conns: 100
  #max_idle_conns:空闲连接池中的最大连接数。如果小于等于0，则不保留空闲连接。
  max_idle_conns: 10
  #max_life_time:设置了连接可复用的最大时间。
  conn_max_lifetime: 10

redis:
  host: localhost
  port: 6379
  db: 0
  pool_size: 10

jwt:
  signing_key: liuBingBlog