log:
  level: "debug"
  err_lever: "error"
  filename: "./log/app.log"
  err_filename: "./log/app.err.log"
  max_size: 10
  max_age: 30
  max_backups: 5

gin:
  host: 0.0.0.0
  port: 8080

mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  db_name: blog
  # max_open_conns:打开到数据库的最大连接数。如果小于等于0，则对打开的连接数没有限制。
  max_open_conns: 100
  # max_idle_conns:空闲连接池中的最大连接数。如果小于等于0，则不保留空闲连接。
  max_idle_conns: 20
  # max_life_time:设置了连接可复用的最大时间。单位：秒
  conn_max_lifetime: 3

redis:
  sentinel_adders:
    - "192.168.11.10:26381"
    - "192.168.11.10:26382"
    - "192.168.11.10:26383"
  master_name: "mymaster"

jwt:
  signing_key: liuBingBlog

secret_key:
  access_key_id: LTAI5tPwFKyq6uQ5PcLcUdTt
  access_key_secret: H4M5f0v6EJiWdI0jWuwbX1ACnHzAbx